#!/usr/bin/env bash
# Brief: Plots the given config using gnuplot.
# Usage: ccd_visual [<xy file>]
# Default xy file: config.xy

xyfile="${1:-config.xy}"
title="$(grep '#Title:' "${xyfile}" | cut -d ' ' -f 2-)"
box="$(grep '#Box:' "${xyfile}" | awk '{print $2}')"

gnuplot --persist << EOF
    set xr[0:"${box}"]
    set yr[0:"${box}"]
    unset tics
    set title "${title}"
    pl "${xyfile}" u 1:2 lt -1 pt 7 ps 0.5 t ""
EOF
