#!/usr/bin/env bash
# Brief: Driver script for <package>
# Usage: <package> [<subcommand> [<options>]]
# Info:
# When user wants to run <package> she usually provides subcommands [with options] to this script
# This script then invokes the necessary executables (found in PATH) with the user-provided options
# This script loads <package>_config.sh on startup and <package>_exit.sh before exit
# Proving no subcommand executes the <package>_ program hidden from the user

whereami(){
  # Returns the absolute path of the directory this script is in
  case "${BASH_SOURCE}" in
    /*)
      echo -n "${BASH_SOURCE%/*}" ;;
    */*)
      echo -n "${PWD}/${BASH_SOURCE%/*}" ;;
    *)
      echo -n "${PWD}";;
  esac
}
this_script_is_at="$(whereami)"

source_if_exists_in_PATH(){
  # Sources the given script if it exists in PATH
  local script="${1}"
  which "${script}" &>/dev/null && source "${script}"
}

invocation="${0}"
package="${invocation##*/}"

export PATH="${this_script_is_at}/${package}_:${PATH}"

source_if_exists_in_PATH ${package}_config.sh

subcmd="${1}"
shift

if [[ -z "${subcmd}" ]]; then
  ${package}_
else
  ${package}_${subcmd} "${@}"
fi

source_if_exists_in_PATH ${package}_exit.sh
